[package]
name = "pallet-xcm-benchmarks"
version = "0.3.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
xcm-executor = { path = "../xcm-executor", default-features = false }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
xcm = { path = "..", default-features = false }
log = "0.4.17"

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
pallet-assets = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate" , branch = "polkadot-v1.0.0" }
xcm-builder = { path = "../xcm-builder" }
xcm = { path = ".." }
# temp
pallet-xcm = { path = "../pallet-xcm" }
selendra-runtime-common = { path = "../../../runtime/common" }
selendra-primitives = { path = "../../../primitives" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std"
]
runtime-benchmarks = [
	"xcm/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
