[package]
name = "selendra-node-subsystem"
version = "0.2.4"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Subsystem traits and message definitions and the generated overseer"

[dependencies]
selendra-overseer = { path = "../overseer" }
selendra-node-subsystem-types = { path = "../subsystem-types" }
selendra-node-jaeger = { path = "../jaeger" }
