edition = "2021"
use_field_init_shorthand = true
reorder_modules = true
reorder_imports = true

# Basic
hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
# Consistency
newline_style = "Unix"
# Misc
chain_width = 80
match_arm_blocks = false
match_block_trailing_comma = true