[package]
name = "forests-pallet-parachain-system-proc-macro"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
description = "Proc macros provided by the parachain-system pallet"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.107"
proc-macro2 = "1.0.49"
quote = "1.0.20"
proc-macro-crate = "1.1.3"

[features]
default = [ "std" ]
std = []
