[package]
name = "selendra-service"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
rand = "0.8"
log = "0.4.17"
async-trait = { version = "0.1.48" }
hex-literal = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.68"
codec = { package = "parity-scale-codec", version = "3.0.0" }
futures = "0.3.21"
hex = "0.4.0"
jsonrpsee = { version = "0.13.0", features = ["server", "macros"] }

coins-bip32 = "0.6.0"
coins-bip39 = "0.6.0"
elliptic-curve = { version = "0.11.12", default-features = false, features = ["hazmat", "sec1"] }
k256 = { version = "0.10.4", default-features = false, features = ["keccak256", "ecdsa", "std"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }

sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }

sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-sysinfo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24"}
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }

module-evm = { path = "../../modules/evm" }
module-nft = { path = "../../modules/nft" }
orml-oracle-rpc = { path = "../../orml/oracle/rpc" }
orml-tokens-rpc = { path = "../../orml/tokens/rpc" }
selendra-primitives = { path = "../../primitives" }
selendra-rpc = { path = "../rpc" }
module-evm-rpc-runtime-api = { path = "../../modules/evm/rpc/runtime_api" }

runtime-common = { path = "../../runtime/common" }
cardamom-runtime = { path = "../../runtime/cardamom", optional = true }
selendra-runtime = { path = "../../runtime/selendra", optional = true }

[features]
default = [ "std", "with-selendra-runtime" ]
std = []

runtime-benchmarks = [
	"cardamom-runtime/runtime-benchmarks",
	"selendra-runtime/runtime-benchmarks",
]

try-runtime = [
	"cardamom-runtime/try-runtime",
	"selendra-runtime/try-runtime",
]
with-cardamom-runtime = [
	"cardamom-runtime",
]
with-selendra-runtime = [
	"selendra-runtime",
]

fast-runtime = [
	"selendra-runtime/fast-runtime",
	"cardamom-runtime/fast-runtime",
]
