[package]
name = "pallet-selendra"
version = "0.1.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
license = "Apache 2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["derive"] }
serde = "1.0"
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-session = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }

pallets-support = { workspace = true }
selendra-primitives = { workspace = true }

[dev-dependencies]
pallet-timestamp = { workspace = true }
sp-runtime = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "selendra-primitives/std",
    "pallet-balances/std",
    "pallet-session/std",
    "pallets-support/std",
]
try-runtime = [
    "frame-support/try-runtime",
    "pallets-support/try-runtime",
]
