[package]
name = "forests-client-pov-recovery"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "Forests-specific networking protocol"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", features = [ "derive" ] }
futures = "0.3.21"
futures-timer = "3.0.2"
rand = "0.8.5"
tracing = "0.1.37"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

# Selendra
selendra-node-primitives = { path = "../../../node/node-helper/primitives" }
selendra-node-subsystem = { path = "../../../node/node-helper/subsystem" }
selendra-overseer = { path = "../../../node/node-helper/overseer" }
selendra-primitives = { path = "../../../primitives" }

# Forests
forests-primitives-core = { path = "../../primitives/core" }
forests-relay-chain-interface = {path = "../relay-chain-interface"}

[dev-dependencies]
portpicker = "0.1.1"
tokio = { version = "1.21.2", features = ["macros"] }
metered = { package = "prioritized-metered-channel", version = "0.2.0" }

# Substrate
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
substrate-test-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

# Forests
forests-test-service = { path = "../../../tests/test-helpers/forests/service" }
