[package]
name = "selendra-core-primitives"
version = "0.2.5"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3.1.5", default-features = false, features = [ "derive" ] }
parity-util-mem = { version = "0.12.0", default-features = false, optional = true }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }

[features]
default = ["std"]
std = [
	"scale-info/std",
	"parity-scale-codec/std",
	"parity-util-mem",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

