[package]
name = "slot-range-helper"
version = "0.2.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"

[dependencies]
paste = "1.0"
enumn = "0.1.4"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28", default-features = false  }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.28", default-features = false  }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"parity-scale-codec/std",
	"sp-runtime/std",
]
